---
apiVersion: ramendr.openshift.io/v1alpha1
kind: DRPlacementControl
metadata:
  name: busybox-drpc
  labels:
    app: busybox-sample
spec:
  preferredCluster: asagare-cl1
  drPolicyRef:
    name: odr-policy-mdr
  placementRef:
    kind: Placement
    name: busybox-placement
  pvcSelector:
    matchLabels:
      appname: busybox_app1
