---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: busybox-cephfs-pvc
  labels:
    appname: busybox-cephfs
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: san-testsdh
  resources:
    requests:
      storage: 5Gi
