apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    appname: busybox-cephfs
  name: busybox-cephfs
spec:
  selector:
    matchLabels:
      workload: busybox-cephfs
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        workload: busybox-cephfs
    spec:
      containers:
      - image: quay.io/vcppds7878/busybox:latest
        imagePullPolicy: IfNotPresent
        name: busybox
