apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    appname: busybox_app1-1
  name: busybox-rbd-pod-1
spec:
  selector:
    matchLabels:
      workload: busybox-rbd
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        workload: busybox-rbd
    spec:
      containers:
      - image: quay.io/ocsci/rdr-ocs-workload
        imagePullPolicy: IfNotPresent
        name: busybox
